-- Generated from Wowhead TBC data. Do not edit by hand.
local RUI = RetreatUI
if not RUI then return end

RUI.generatedTBCData = RUI.generatedTBCData or {}
RUI.generatedTBCData.generatedAt = [=[2026-08-06T08:31:57Z]=]
RUI.generatedTBCData.libSpellDBRevision = [=[edc189b928df86376339d00c0760c2d894ae0bad]=]
RUI.generatedTBCData.wowSimsRevision = [=[509f669a6a5e1a766b3dd71ff0bc5baa74985d56]=]

RUI.generatedTBCData.racials = {
    {
        race = [=[BloodElf]=],
        name = [=[Arcane Torrent]=],
        spellID = 25046,
        canonicalID = 25046,
        category = [=[Interrupt]=],
        hudRow = [=[Utility]=],
        cooldown = 120,
        duration = 2,
    },
    {
        race = [=[BloodElf]=],
        name = [=[Arcane Torrent]=],
        spellID = 28730,
        canonicalID = 28730,
        category = [=[Interrupt]=],
        hudRow = [=[Utility]=],
        cooldown = 120,
        duration = 2,
    },
    {
        race = [=[BloodElf]=],
        name = [=[Consume Magic]=],
        spellID = 32676,
        canonicalID = 32676,
        category = [=[Utility]=],
        hudRow = [=[Utility]=],
        cooldown = 120,
        duration = 0,
    },
    {
        race = [=[BloodElf]=],
        name = [=[Mana Tap]=],
        spellID = 28734,
        canonicalID = 28734,
        category = [=[Utility]=],
        hudRow = [=[Utility]=],
        cooldown = 30,
        duration = 600,
    },
    {
        race = [=[Draenei]=],
        name = [=[Gift of the Naaru]=],
        spellID = 28880,
        canonicalID = 28880,
        category = [=[Defensive]=],
        hudRow = [=[Utility]=],
        cooldown = 180,
        duration = 15,
    },
    {
        race = [=[Draenei]=],
        name = [=[Symbol of Hope]=],
        spellID = 32548,
        canonicalID = 32548,
        category = [=[Resource]=],
        hudRow = [=[Main]=],
        cooldown = 300,
        duration = 15,
    },
    {
        race = [=[Dwarf]=],
        name = [=[Stoneform]=],
        spellID = 20594,
        canonicalID = 20594,
        category = [=[Defensive]=],
        hudRow = [=[Utility]=],
        cooldown = 180,
        duration = 8,
    },
    {
        race = [=[Gnome]=],
        name = [=[Escape Artist]=],
        spellID = 20589,
        canonicalID = 20589,
        category = [=[Defensive]=],
        hudRow = [=[Utility]=],
        cooldown = 105,
        duration = 0,
    },
    {
        race = [=[Human]=],
        name = [=[Feedback]=],
        spellID = 13896,
        canonicalID = 13896,
        category = [=[Defensive]=],
        hudRow = [=[Utility]=],
        cooldown = 180,
        duration = 15,
    },
    {
        race = [=[Human]=],
        name = [=[Feedback]=],
        spellID = 19271,
        canonicalID = 13896,
        category = [=[Defensive]=],
        hudRow = [=[Utility]=],
        cooldown = 180,
        duration = 15,
    },
    {
        race = [=[Human]=],
        name = [=[Feedback]=],
        spellID = 19273,
        canonicalID = 13896,
        category = [=[Defensive]=],
        hudRow = [=[Utility]=],
        cooldown = 180,
        duration = 15,
    },
    {
        race = [=[Human]=],
        name = [=[Feedback]=],
        spellID = 19274,
        canonicalID = 13896,
        category = [=[Defensive]=],
        hudRow = [=[Utility]=],
        cooldown = 180,
        duration = 15,
    },
    {
        race = [=[Human]=],
        name = [=[Feedback]=],
        spellID = 19275,
        canonicalID = 13896,
        category = [=[Defensive]=],
        hudRow = [=[Utility]=],
        cooldown = 180,
        duration = 15,
    },
    {
        race = [=[Human]=],
        name = [=[Feedback]=],
        spellID = 25441,
        canonicalID = 13896,
        category = [=[Defensive]=],
        hudRow = [=[Utility]=],
        cooldown = 180,
        duration = 15,
    },
    {
        race = [=[Human]=],
        name = [=[Perception]=],
        spellID = 20600,
        canonicalID = 20600,
        category = [=[Utility]=],
        hudRow = [=[Utility]=],
        cooldown = 180,
        duration = 20,
    },
    {
        race = [=[NightElf]=],
        name = [=[Elune's Grace]=],
        spellID = 2651,
        canonicalID = 2651,
        category = [=[Defensive]=],
        hudRow = [=[Utility]=],
        cooldown = 180,
        duration = 15,
    },
    {
        race = [=[NightElf]=],
        name = [=[Shadowmeld]=],
        spellID = 20580,
        canonicalID = 20580,
        category = [=[Utility]=],
        hudRow = [=[Utility]=],
        cooldown = 10,
        duration = 0,
    },
    {
        race = [=[NightElf]=],
        name = [=[Starshards]=],
        spellID = 10797,
        canonicalID = 10797,
        category = [=[Offensive]=],
        hudRow = [=[Main]=],
        cooldown = 30,
        duration = 15,
    },
    {
        race = [=[NightElf]=],
        name = [=[Starshards]=],
        spellID = 19296,
        canonicalID = 10797,
        category = [=[Offensive]=],
        hudRow = [=[Main]=],
        cooldown = 30,
        duration = 15,
    },
    {
        race = [=[NightElf]=],
        name = [=[Starshards]=],
        spellID = 19299,
        canonicalID = 10797,
        category = [=[Offensive]=],
        hudRow = [=[Main]=],
        cooldown = 30,
        duration = 15,
    },
    {
        race = [=[NightElf]=],
        name = [=[Starshards]=],
        spellID = 19302,
        canonicalID = 10797,
        category = [=[Offensive]=],
        hudRow = [=[Main]=],
        cooldown = 30,
        duration = 15,
    },
    {
        race = [=[NightElf]=],
        name = [=[Starshards]=],
        spellID = 19303,
        canonicalID = 10797,
        category = [=[Offensive]=],
        hudRow = [=[Main]=],
        cooldown = 30,
        duration = 15,
    },
    {
        race = [=[NightElf]=],
        name = [=[Starshards]=],
        spellID = 19304,
        canonicalID = 10797,
        category = [=[Offensive]=],
        hudRow = [=[Main]=],
        cooldown = 30,
        duration = 15,
    },
    {
        race = [=[NightElf]=],
        name = [=[Starshards]=],
        spellID = 19305,
        canonicalID = 10797,
        category = [=[Offensive]=],
        hudRow = [=[Main]=],
        cooldown = 30,
        duration = 15,
    },
    {
        race = [=[NightElf]=],
        name = [=[Starshards]=],
        spellID = 25446,
        canonicalID = 10797,
        category = [=[Offensive]=],
        hudRow = [=[Main]=],
        cooldown = 30,
        duration = 15,
    },
    {
        race = [=[Orc]=],
        name = [=[Blood Fury]=],
        spellID = 20572,
        canonicalID = 20572,
        category = [=[Offensive]=],
        hudRow = [=[Main]=],
        cooldown = 120,
        duration = 15,
    },
    {
        race = [=[Orc]=],
        name = [=[Blood Fury]=],
        spellID = 33697,
        canonicalID = 33697,
        category = [=[Offensive]=],
        hudRow = [=[Main]=],
        cooldown = 120,
        duration = 15,
    },
    {
        race = [=[Orc]=],
        name = [=[Blood Fury]=],
        spellID = 33702,
        canonicalID = 33702,
        category = [=[Offensive]=],
        hudRow = [=[Main]=],
        cooldown = 120,
        duration = 15,
    },
    {
        race = [=[Scourge]=],
        name = [=[Cannibalize]=],
        spellID = 20577,
        canonicalID = 20577,
        category = [=[Utility]=],
        hudRow = [=[Utility]=],
        cooldown = 120,
        duration = 10,
    },
    {
        race = [=[Scourge]=],
        name = [=[Devouring Plague]=],
        spellID = 2944,
        canonicalID = 2944,
        category = [=[Offensive]=],
        hudRow = [=[Main]=],
        cooldown = 180,
        duration = 24,
    },
    {
        race = [=[Scourge]=],
        name = [=[Devouring Plague]=],
        spellID = 19276,
        canonicalID = 2944,
        category = [=[Offensive]=],
        hudRow = [=[Main]=],
        cooldown = 180,
        duration = 24,
    },
    {
        race = [=[Scourge]=],
        name = [=[Devouring Plague]=],
        spellID = 19277,
        canonicalID = 2944,
        category = [=[Offensive]=],
        hudRow = [=[Main]=],
        cooldown = 180,
        duration = 24,
    },
    {
        race = [=[Scourge]=],
        name = [=[Devouring Plague]=],
        spellID = 19278,
        canonicalID = 2944,
        category = [=[Offensive]=],
        hudRow = [=[Main]=],
        cooldown = 180,
        duration = 24,
    },
    {
        race = [=[Scourge]=],
        name = [=[Devouring Plague]=],
        spellID = 19279,
        canonicalID = 2944,
        category = [=[Offensive]=],
        hudRow = [=[Main]=],
        cooldown = 180,
        duration = 24,
    },
    {
        race = [=[Scourge]=],
        name = [=[Devouring Plague]=],
        spellID = 19280,
        canonicalID = 2944,
        category = [=[Offensive]=],
        hudRow = [=[Main]=],
        cooldown = 180,
        duration = 24,
    },
    {
        race = [=[Scourge]=],
        name = [=[Devouring Plague]=],
        spellID = 25467,
        canonicalID = 2944,
        category = [=[Offensive]=],
        hudRow = [=[Main]=],
        cooldown = 180,
        duration = 24,
    },
    {
        race = [=[Scourge]=],
        name = [=[Will of the Forsaken]=],
        spellID = 7744,
        canonicalID = 7744,
        category = [=[Defensive]=],
        hudRow = [=[Utility]=],
        cooldown = 120,
        duration = 5,
    },
    {
        race = [=[Tauren]=],
        name = [=[War Stomp]=],
        spellID = 20549,
        canonicalID = 20549,
        category = [=[Crowd Control]=],
        hudRow = [=[Utility]=],
        cooldown = 120,
        duration = 2,
    },
    {
        race = [=[Troll]=],
        name = [=[Berserking]=],
        spellID = 26297,
        canonicalID = 26297,
        category = [=[Offensive]=],
        hudRow = [=[Main]=],
        cooldown = 180,
        duration = 10,
    },
    {
        race = [=[Troll]=],
        name = [=[Hex of Weakness]=],
        spellID = 9035,
        canonicalID = 9035,
        category = [=[Utility]=],
        hudRow = [=[Utility]=],
        cooldown = 0,
        duration = 120,
    },
    {
        race = [=[Troll]=],
        name = [=[Hex of Weakness]=],
        spellID = 19281,
        canonicalID = 9035,
        category = [=[Utility]=],
        hudRow = [=[Utility]=],
        cooldown = 0,
        duration = 120,
    },
    {
        race = [=[Troll]=],
        name = [=[Hex of Weakness]=],
        spellID = 19282,
        canonicalID = 9035,
        category = [=[Utility]=],
        hudRow = [=[Utility]=],
        cooldown = 0,
        duration = 120,
    },
    {
        race = [=[Troll]=],
        name = [=[Hex of Weakness]=],
        spellID = 19283,
        canonicalID = 9035,
        category = [=[Utility]=],
        hudRow = [=[Utility]=],
        cooldown = 0,
        duration = 120,
    },
    {
        race = [=[Troll]=],
        name = [=[Hex of Weakness]=],
        spellID = 19284,
        canonicalID = 9035,
        category = [=[Utility]=],
        hudRow = [=[Utility]=],
        cooldown = 0,
        duration = 120,
    },
    {
        race = [=[Troll]=],
        name = [=[Hex of Weakness]=],
        spellID = 19285,
        canonicalID = 9035,
        category = [=[Utility]=],
        hudRow = [=[Utility]=],
        cooldown = 0,
        duration = 120,
    },
    {
        race = [=[Troll]=],
        name = [=[Hex of Weakness]=],
        spellID = 25470,
        canonicalID = 9035,
        category = [=[Utility]=],
        hudRow = [=[Utility]=],
        cooldown = 0,
        duration = 120,
    },
    {
        race = [=[Troll]=],
        name = [=[Shadowguard]=],
        spellID = 18137,
        canonicalID = 18137,
        category = [=[Offensive]=],
        hudRow = [=[Main]=],
        cooldown = 0,
        duration = 600,
    },
    {
        race = [=[Troll]=],
        name = [=[Shadowguard]=],
        spellID = 19308,
        canonicalID = 18137,
        category = [=[Offensive]=],
        hudRow = [=[Main]=],
        cooldown = 0,
        duration = 600,
    },
    {
        race = [=[Troll]=],
        name = [=[Shadowguard]=],
        spellID = 19309,
        canonicalID = 18137,
        category = [=[Offensive]=],
        hudRow = [=[Main]=],
        cooldown = 0,
        duration = 600,
    },
    {
        race = [=[Troll]=],
        name = [=[Shadowguard]=],
        spellID = 19310,
        canonicalID = 18137,
        category = [=[Offensive]=],
        hudRow = [=[Main]=],
        cooldown = 0,
        duration = 600,
    },
    {
        race = [=[Troll]=],
        name = [=[Shadowguard]=],
        spellID = 19311,
        canonicalID = 18137,
        category = [=[Offensive]=],
        hudRow = [=[Main]=],
        cooldown = 0,
        duration = 600,
    },
    {
        race = [=[Troll]=],
        name = [=[Shadowguard]=],
        spellID = 19312,
        canonicalID = 18137,
        category = [=[Offensive]=],
        hudRow = [=[Main]=],
        cooldown = 0,
        duration = 600,
    },
    {
        race = [=[Troll]=],
        name = [=[Shadowguard]=],
        spellID = 25477,
        canonicalID = 18137,
        category = [=[Offensive]=],
        hudRow = [=[Main]=],
        cooldown = 0,
        duration = 600,
    },
    {
        race = [=[['Dwarf', 'Draenei']]=],
        name = [=[Chastise]=],
        spellID = 44041,
        canonicalID = 44046,
        category = [=[Crowd Control]=],
        hudRow = [=[Utility]=],
        cooldown = 30,
        duration = 2,
    },
    {
        race = [=[['Dwarf', 'Draenei']]=],
        name = [=[Chastise]=],
        spellID = 44043,
        canonicalID = 44046,
        category = [=[Crowd Control]=],
        hudRow = [=[Utility]=],
        cooldown = 30,
        duration = 2,
    },
    {
        race = [=[['Dwarf', 'Draenei']]=],
        name = [=[Chastise]=],
        spellID = 44044,
        canonicalID = 44046,
        category = [=[Crowd Control]=],
        hudRow = [=[Utility]=],
        cooldown = 30,
        duration = 2,
    },
    {
        race = [=[['Dwarf', 'Draenei']]=],
        name = [=[Chastise]=],
        spellID = 44045,
        canonicalID = 44046,
        category = [=[Crowd Control]=],
        hudRow = [=[Utility]=],
        cooldown = 30,
        duration = 2,
    },
    {
        race = [=[['Dwarf', 'Draenei']]=],
        name = [=[Chastise]=],
        spellID = 44046,
        canonicalID = 44046,
        category = [=[Crowd Control]=],
        hudRow = [=[Utility]=],
        cooldown = 30,
        duration = 2,
    },
    {
        race = [=[['Dwarf', 'Human']]=],
        name = [=[Desperate Prayer]=],
        spellID = 13908,
        canonicalID = 13908,
        category = [=[Defensive]=],
        hudRow = [=[Utility]=],
        cooldown = 600,
        duration = 0,
    },
    {
        race = [=[['Dwarf', 'Human']]=],
        name = [=[Desperate Prayer]=],
        spellID = 19236,
        canonicalID = 13908,
        category = [=[Defensive]=],
        hudRow = [=[Utility]=],
        cooldown = 600,
        duration = 0,
    },
    {
        race = [=[['Dwarf', 'Human']]=],
        name = [=[Desperate Prayer]=],
        spellID = 19238,
        canonicalID = 13908,
        category = [=[Defensive]=],
        hudRow = [=[Utility]=],
        cooldown = 600,
        duration = 0,
    },
    {
        race = [=[['Dwarf', 'Human']]=],
        name = [=[Desperate Prayer]=],
        spellID = 19240,
        canonicalID = 13908,
        category = [=[Defensive]=],
        hudRow = [=[Utility]=],
        cooldown = 600,
        duration = 0,
    },
    {
        race = [=[['Dwarf', 'Human']]=],
        name = [=[Desperate Prayer]=],
        spellID = 19241,
        canonicalID = 13908,
        category = [=[Defensive]=],
        hudRow = [=[Utility]=],
        cooldown = 600,
        duration = 0,
    },
    {
        race = [=[['Dwarf', 'Human']]=],
        name = [=[Desperate Prayer]=],
        spellID = 19242,
        canonicalID = 13908,
        category = [=[Defensive]=],
        hudRow = [=[Utility]=],
        cooldown = 600,
        duration = 0,
    },
    {
        race = [=[['Dwarf', 'Human']]=],
        name = [=[Desperate Prayer]=],
        spellID = 19243,
        canonicalID = 13908,
        category = [=[Defensive]=],
        hudRow = [=[Utility]=],
        cooldown = 600,
        duration = 0,
    },
    {
        race = [=[['Dwarf', 'Human']]=],
        name = [=[Desperate Prayer]=],
        spellID = 25437,
        canonicalID = 13908,
        category = [=[Defensive]=],
        hudRow = [=[Utility]=],
        cooldown = 600,
        duration = 0,
    },
    {
        race = [=[['Scourge', 'BloodElf']]=],
        name = [=[Touch of Weakness]=],
        spellID = 2652,
        canonicalID = 2652,
        category = [=[Defensive]=],
        hudRow = [=[Utility]=],
        cooldown = 0,
        duration = 600,
    },
    {
        race = [=[['Scourge', 'BloodElf']]=],
        name = [=[Touch of Weakness]=],
        spellID = 19261,
        canonicalID = 2652,
        category = [=[Defensive]=],
        hudRow = [=[Utility]=],
        cooldown = 0,
        duration = 600,
    },
    {
        race = [=[['Scourge', 'BloodElf']]=],
        name = [=[Touch of Weakness]=],
        spellID = 19262,
        canonicalID = 2652,
        category = [=[Defensive]=],
        hudRow = [=[Utility]=],
        cooldown = 0,
        duration = 600,
    },
    {
        race = [=[['Scourge', 'BloodElf']]=],
        name = [=[Touch of Weakness]=],
        spellID = 19264,
        canonicalID = 2652,
        category = [=[Defensive]=],
        hudRow = [=[Utility]=],
        cooldown = 0,
        duration = 600,
    },
    {
        race = [=[['Scourge', 'BloodElf']]=],
        name = [=[Touch of Weakness]=],
        spellID = 19265,
        canonicalID = 2652,
        category = [=[Defensive]=],
        hudRow = [=[Utility]=],
        cooldown = 0,
        duration = 600,
    },
    {
        race = [=[['Scourge', 'BloodElf']]=],
        name = [=[Touch of Weakness]=],
        spellID = 19266,
        canonicalID = 2652,
        category = [=[Defensive]=],
        hudRow = [=[Utility]=],
        cooldown = 0,
        duration = 600,
    },
    {
        race = [=[['Scourge', 'BloodElf']]=],
        name = [=[Touch of Weakness]=],
        spellID = 25461,
        canonicalID = 2652,
        category = [=[Defensive]=],
        hudRow = [=[Utility]=],
        cooldown = 0,
        duration = 600,
    },
}

RUI.generatedTBCData.trinkets = {
    [32490] = {
        name = [=[Ashtongue Talisman of Acumen]=],
        procBuffID = 40441,
        onUseBuffID = 0,
        icd = 0,
        onTarget = false,
    },
    [32486] = {
        name = [=[Ashtongue Talisman of Equilibrium]=],
        procBuffID = 40452,
        onUseBuffID = 0,
        icd = 0,
        onTarget = false,
    },
    [32488] = {
        name = [=[Ashtongue Talisman of Insight]=],
        procBuffID = 40483,
        onUseBuffID = 0,
        icd = 0,
        onTarget = false,
    },
    [32492] = {
        name = [=[Ashtongue Talisman of Lethality]=],
        procBuffID = 40461,
        onUseBuffID = 0,
        icd = 0,
        onTarget = false,
    },
    [32493] = {
        name = [=[Ashtongue Talisman of Shadows]=],
        procBuffID = 40480,
        onUseBuffID = 0,
        icd = 0,
        onTarget = false,
    },
    [32487] = {
        name = [=[Ashtongue Talisman of Swiftness]=],
        procBuffID = 40487,
        onUseBuffID = 0,
        icd = 0,
        onTarget = false,
    },
    [32485] = {
        name = [=[Ashtongue Talisman of Valor]=],
        procBuffID = 40459,
        onUseBuffID = 0,
        icd = 0,
        onTarget = false,
    },
    [32491] = {
        name = [=[Ashtongue Talisman of Vision]=],
        procBuffID = 40466,
        onUseBuffID = 0,
        icd = 0,
        onTarget = false,
    },
    [32489] = {
        name = [=[Ashtongue Talisman of Zeal]=],
        procBuffID = 40471,
        onUseBuffID = 0,
        icd = 0,
        onTarget = true,
    },
    [28370] = {
        name = [=[Bangle of Endless Blessings]=],
        procBuffID = 38346,
        onUseBuffID = 0,
        icd = 45,
        onTarget = false,
    },
    [34427] = {
        name = [=[Blackened Naaru Sliver]=],
        procBuffID = 45040,
        onUseBuffID = 0,
        icd = 45,
        onTarget = false,
    },
    [34473] = {
        name = [=[Commendation of Kael'thas]=],
        procBuffID = 45058,
        onUseBuffID = 0,
        icd = 30,
        onTarget = false,
    },
    [19288] = {
        name = [=[Darkmoon Card: Blue Dragon]=],
        procBuffID = 23684,
        onUseBuffID = 0,
        icd = 0,
        onTarget = false,
    },
    [31856] = {
        name = [=[Darkmoon Card: Crusade]=],
        procBuffID = 39439,
        onUseBuffID = 0,
        icd = 0,
        onTarget = false,
    },
    [31857] = {
        name = [=[Darkmoon Card: Wrath]=],
        procBuffID = 39443,
        onUseBuffID = 0,
        icd = 0,
        onTarget = false,
    },
    [28830] = {
        name = [=[Dragonspine Trophy]=],
        procBuffID = 34775,
        onUseBuffID = 0,
        icd = 20,
        onTarget = false,
    },
    [28823] = {
        name = [=[Eye of Gruul]=],
        procBuffID = 37706,
        onUseBuffID = 0,
        icd = 0,
        onTarget = false,
    },
    [28789] = {
        name = [=[Eye of Magtheridon]=],
        procBuffID = 34747,
        onUseBuffID = 0,
        icd = 0,
        onTarget = false,
    },
    [30619] = {
        name = [=[Fel Reaver's Piston]=],
        procBuffID = 38324,
        onUseBuffID = 0,
        icd = 15,
        onTarget = true,
    },
    [28034] = {
        name = [=[Hourglass of the Unraveller]=],
        procBuffID = 33649,
        onUseBuffID = 0,
        icd = 45,
        onTarget = false,
    },
    [30664] = {
        name = [=[Living Root of the Wildheart]=],
        procBuffID = 37344,
        onUseBuffID = 0,
        icd = 0,
        onTarget = false,
    },
    [32505] = {
        name = [=[Madness of the Betrayer]=],
        procBuffID = 40477,
        onUseBuffID = 0,
        icd = 0,
        onTarget = false,
    },
    [32496] = {
        name = [=[Memento of Tyrande]=],
        procBuffID = 37656,
        onUseBuffID = 0,
        icd = 50,
        onTarget = false,
    },
    [27683] = {
        name = [=[Quagmirran's Eye]=],
        procBuffID = 33370,
        onUseBuffID = 0,
        icd = 45,
        onTarget = false,
    },
    [28190] = {
        name = [=[Scarab of the Infinite Cycle]=],
        procBuffID = 33370,
        onUseBuffID = 0,
        icd = 45,
        onTarget = false,
    },
    [30626] = {
        name = [=[Sextant of Unstable Currents]=],
        procBuffID = 38348,
        onUseBuffID = 0,
        icd = 45,
        onTarget = false,
    },
    [34472] = {
        name = [=[Shard of Contempt]=],
        procBuffID = 45053,
        onUseBuffID = 0,
        icd = 45,
        onTarget = false,
    },
    [28418] = {
        name = [=[Shiffar's Nexus-Horn]=],
        procBuffID = 34321,
        onUseBuffID = 0,
        icd = 45,
        onTarget = false,
    },
    [30448] = {
        name = [=[Talon of Al'ar]=],
        procBuffID = 37508,
        onUseBuffID = 0,
        icd = 0,
        onTarget = false,
    },
    [28785] = {
        name = [=[The Lightning Capacitor]=],
        procBuffID = 37658,
        onUseBuffID = 0,
        icd = 0,
        onTarget = false,
    },
    [34470] = {
        name = [=[Timbal's Focusing Crystal]=],
        procBuffID = 45055,
        onUseBuffID = 0,
        icd = 15,
        onTarget = false,
    },
    [30447] = {
        name = [=[Tome of Fiery Redemption]=],
        procBuffID = 37198,
        onUseBuffID = 0,
        icd = 45,
        onTarget = false,
    },
    [30627] = {
        name = [=[Tsunami Talisman]=],
        procBuffID = 42084,
        onUseBuffID = 0,
        icd = 45,
        onTarget = false,
    },
    [30450] = {
        name = [=[Warp-Spring Coil]=],
        procBuffID = 37174,
        onUseBuffID = 0,
        icd = 30,
        onTarget = false,
    },
}
