name: Completed RetreatUI v1.0.11-beta.6 publication

on:
  workflow_dispatch:

jobs:
  completed:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'RetreatUI v1.0.11-beta.6 has already been published.'
